### ISSUE TITLE
想请教大佬一个小小的关于使用高通MDM9150芯片 v2x模组的程序运行问题

### ISSUE THREAD

**Issue by rustInTheRubble** [feishengfei/sdk_guide_sdx55#1]
您好，我是在asciinema看到了您关于cv2x 高通 mdm9150的终端会话记录，我现在有一组SIM8100的v2x模组，使用的也是高通的MDM9150芯片。

我按照高通给的Telematics SDK手册，制作了SDK，在ubuntu14上把高通给snaptel-sdk-LE.UM.1.3.2.r1-11400-9150-cv2x中关于v2x的c++  demo编译后，push到板子上，对于Cv2xGetStatusApp的代码
```

1. int main(int argc, char *argv[]) {
2.     cout << "Running Sample C-V2X RX app" << endl;
3. 
4.     // Get handle to Cv2xRadioManager
5.     auto & cv2xFactory = Cv2xFactory::getInstance();
6.     auto cv2xRadioManager = cv2xFactory.getCv2xRadioManager();
7. 
8.     // Wait for radio manager to complete initialization
9.     **if (not cv2xRadioManager->isReady()) {**
10.         if (!cv2xRadioManager->onReady().get()) {
11.             cout << "Error : C-V2X Radio Manager initialization failed" << endl;
12.             return EXIT_FAILURE;
13.         }
14.     }

```

执行到第9行 `cv2xRadioManager->isReady()`的会出现 `Segmentation fault (core dumped)`的错误。

使用gdb调试，只能看到卡在
```
Running Sample C-V2X RX app

Program received signal SIGSEGV, Segmentation fault.
#0  0xb6f1026c in telux::cv2x::Cv2xRadioManager::getCv2xRadio(telux::cv2x::TrafficCategory) () from /usr/lib/libtelux_cv2x.so
#1  0x00000002 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

这个问题困扰我很久了，您有遇到过类似的情况吗？
我现在只是想实现自己收发数据，但我遇到了太多问题。

**Comment by feishengfei** [comment]
试试编译libtelux_cv2x工程时加入-g选项开启调试, 并把动态库以及全套程序都推到板子上。
ulimit -c unlimited
core文件以及所有二进制／动态库确保板子中和PC中一致。
在pc上解dump:
```
gdb your_binary -c your_binary.core
```
注意执行
```
set solib-search-path /your/path/to/your/library
```
这样可以定位动态库中出现的SEGV异常

**Comment by rustInTheRubble** [comment]
谢谢解答，我最后发现是由于板子和PC中的v2x相关库不一致导致的，保持一致后就没有错了

**Comment by ABfuz** [comment]
> 谢谢解答，我最后发现是由于板子和PC中的v2x相关库不一致导致的，保持一致后就没有错了

我也遇到了这个问题，能帮忙看一下吗

**Comment by feishengfei** [comment]
> > 谢谢解答，我最后发现是由于板子和PC中的v2x相关库不一致导致的，保持一致后就没有错了
> 
> 我也遇到了这个问题，能帮忙看一下吗

已经不再从事高通通信产品的开发工作了，但是如果您也是段错误类的问题，还是首先看可不可以做出coredump看看栈顶是什么情况，按通用类型的问题来处理。
